// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:25f2a4da-6be5-4dec-a460-eee732147f18",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_q9JqOxIpF",
    "aws_user_pools_web_client_id": "ec027ft9advb40j2bhcj5ertm",
    "oauth": {},
    "aws_content_delivery_bucket": "offsuitnine-hosting-bucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://offsuitnine-hosting-bucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://l7v26rvkezcunl5zdffut6d6pu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
